spring:
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        hbm2ddl:
#         auto: none
#        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui
logging:
  level:
    root: info
    org.springframework.web: trace
  file:
    name: application.log
    path: classpath:logs/application.log







