spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: profile
        format_sql: false
        hbm2ddl:
         auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui